# Using slim here because we need chromium for puppeteer
#
FROM selenium/node-chrome

USER root

RUN apt-get update
RUN apt-get install --yes curl

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y nodejs yarn

RUN apt-get install --yes \
    dbus-x11 \
    ttf-freefont \
    python \
    python-dev \
    python-pip \
    git \
    musl \
    build-essential \
    libffi-dev \
    libusb-1.0-0-dev

COPY entry_point.sh /opt/bin/

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# begin create caching layer
COPY package.json /app/package.json
WORKDIR /app
RUN git init \
  && yarn add require-from-string \
  && yarn \
  && rm -rf .git \
  && rm package.json \
  && rm yarn.lock
# end create caching layer

COPY . /app

RUN ETHEREUM_NETWORK=integration yarn build --dev

# Add Chrome as a user. Without this chrome requires that it be run --without-sandbox
# which jest-puppetter doesn't do by default. So, to keep the sandboxing for the
# running of these tests we gotta add a group and user for chrome
USER seluser
# CMD ["xvfb-run --auto-servernum"]
